### ISSUE TITLE
Error on GtkLabel::set_line_wrap_mode

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#114] opened 2024-07-06 14:44 UTC
https://docs.gtk.org/gtk3/method.Label.set_line_wrap_mode.html

values 0-2 cause an error
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1463287808 bytes)
```

same for build-in constant value `\GtkWrapMode::WORD`

reference
https://docs.gtk.org/Pango/enum.WrapMode.html

**Comment by scorninpc** [comment] 2024-07-07 18:21
forneça um código de trabalho reproduzível

**Comment by scorninpc** [comment] 2024-07-09 14:32
Sorry [d47081](https://github.com/d47081), but I REALLY need a small code to reproduce the errors. Every time you open a issue, if you provide a simple GtkWindow with a GtkLabel, with a property/method that causing error, this will be fixed alot more fast

Now for example, I need to merge your commit, but how can i test if this request will fix your problem and will not break another thing?

**Comment by scorninpc** [comment] 2024-07-09 15:06
Look, i cannot reproduce

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/5801e917-45fa-48c0-a053-a525b8ce111c)

```php
<?php

	Gtk::init();

	$window = new GtkWindow();
	$window->set_default_size(500, 500);
	$window->set_title("PHP-GTK");

	//
	$vbox = new GtkBox(GtkOrientation::VERTICAL);

	// 
	$label01 = new GtkLabel("My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test");
	$label01->set_line_wrap_mode(PangoWrapMode::WORD);
	$vbox->pack_start($label01, TRUE, TRUE);

	$label02 = new GtkLabel("My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test");
	$label02->set_line_wrap_mode(PangoWrapMode::CHAR);
	$vbox->pack_start($label02, TRUE, TRUE);

	$label03 = new GtkLabel("My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test, My super test");
	$label03->set_line_wrap_mode(PangoWrapMode::WORD_CHAR);
	$vbox->pack_start($label03, TRUE, TRUE);

	//
	$window->add($vbox);
	
	// connect to signal that close program
	$window->connect("destroy", function() {
		Gtk::main_quit();
	});

	// show all and start
	$window->show_all();
	Gtk::main();
```

**Comment by scorninpc** [comment] 2024-07-09 21:24
No, the namespace in this context is irrelevant

I'm testing your pull request

**Comment by scorninpc** [comment] 2024-07-09 21:29
are you using php-gtk compiled with your pull request?

**Comment by scorninpc** [comment] 2024-07-09 21:41
that's what i'm talking about. With your PR the example works, but i need to test. As you can see on my print, make no difference, so i need to test, only that

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/b58a6571-d372-4b77-a0fc-4b8af346fa08)

**Comment by scorninpc** [comment] 2024-07-10 14:17
Ah very cool 

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/99ea2743-cb7d-48bb-89ec-3def4de093d0)

**Closed by scorninpc** 2024-07-10 14:17 UTC
